### ISSUE TITLE
Fitted function or predicted value

### ISSUE THREAD

**Issue by SvenMatern** [JBjouffray/ggBRT#1]
I realized, that the fitted function values from ggPD_boot are different to the fitted function values from ggPD. (Check your figures from ggPD and ggPD_boot in the tutorial)
Does ggPD_boot maybe use the predicted values instead of the fitted function?

**Comment by SvenMatern** [comment]
In ggPD you use the following code in line 64:
`responses[[j]] <- response.matrix[, 2] - mean(response.matrix[, 2])`

In ggPD_boot you use the following code in lines 85 - 89:
```
 #responses[[j]] <- response.matrix[, 2] - mean(response.matrix[, 2])
#taking away the mean mucks up the real values.

num.values <- nrow(response.matrix)
responses[[j]] <- response.matrix[,2]
```
When you use `response.matrix[, 2] - mean(response.matrix[, 2])` in ggPD_boot it totally messed up the graph, because later on you also enter the `booted.pred` for the confidence intervall. So the booted.preds also need to be "corrected" with the mean to get the fitted function confidence intervall.

**Comment by JBjouffray** [comment]
Hi Sven. Sorry for the delay (I've been off GitHub for a while) and thanks for spotting the discrepancy, you're totally right. I will have to refresh my mind on these functions and try to fix them asap, but if you have managed to fix the codes already, feel free to share and I will implement the modifications. Thanks again and more soon!

**Comment by SvenMatern** [comment]
Hey Jean-Baptiste,

 

I worked a bit on the code, so that it works for my data, however, the new code is a bit sketchy.

I have never implemented a code on github so far. I can give it a try. Lets see, if it will work.

 

I put me with my working email adress in cc, because I hardly check this email adress...

 

Cheers

 

Sven

 

 

 

Gesendet: Sonntag, 10. Mai 2020 um 17:31 Uhr
Von: "Jean-Baptiste Jouffray" <notifications@github.com>
An: "JBjouffray/ggBRT" <ggBRT@noreply.github.com>
Cc: "SvenMatern" <locken-bock@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [JBjouffray/ggBRT] Fitted function or predicted value (#1)


 

Hi Sven. Sorry for the delay (I've been off GitHub for a while) and thanks for spotting the discrepancy, you're totally right. I will have to refresh my minds on these functions and try to fix them asap, but if you have managed to fix the codes already, feel free to share and I will implement the modifications. Thanks again and more soon!

**Comment by joleehaz** [comment]
@SvenMatern did you manage to fix this issue? I am having the same problem. I would be eternally grateful for any assistance you can offer!

**Comment by joleehaz** [comment]
I have resolved the issue with the following edits to the source code.

Line 85 - 95

```
      responses[[j]] <- response.matrix[, 2] - mean(response.matrix[, 2]) # added back in
      #taking away the mean mucks up the real values.
      
      num.values <- nrow(response.matrix)
      #responses[[j]] <- response.matrix[,2] # removed

# minus mean as suggested by SvenMatern 

      temp <-apply(booted.preds[,k,]- mean(booted.preds[,k,]), 1, function(x){quantile(x, cis[1],na.rm=T)}) 
      responses.lower[[j]] <- temp[1:num.values]
      
      temp <-apply(booted.preds[,k,]- mean(booted.preds[,k,]), 1, function(x){quantile(x, cis[2],na.rm=T)}) 
      responses.upper[[j]] <- temp[1:num.values]
```
