### ISSUE TITLE
ggPD_boot cex.smooth hard coded

### ISSUE THREAD

**Issue by asolsonaberga** [JBjouffray/ggBRT#3]
Hi @JBjouffray ,

I wanted to extend a heartfelt thank you for making this code publicly available. It’s truly been invaluable to make pretty plots of the BRT models, and I’m very grateful for the time and effort you put into creating and sharing this resource with the community.

I have a few small suggestions that might help make it even more flexible, if you’re open to them:

In the ggPD_boot function, I noticed that the smooth line size is currently hard-coded to 0.3. While ggPD allows this to be adjusted using cex.smooth, it doesn’t seem to be the case with ggPD_boot. I believe this could be modified in lines 264-266, where it’s currently set to:

        if (smooth==T){
          ggPD<-ggPD+geom_smooth(span=span,size=0.3,color=col.smooth,se=F,linetype=2)
        }

It might be possible to replace it with. This will need to be modified in lines 168, 194, 265, 291:

        if (smooth==T){
          ggPD<-ggPD+geom_smooth(span=span,size=cex.smooth,color=col.smooth,se=F,linetype=2)
        }

Additionally, it would be fantastic to have the ability to modify the rug color, as the current light color can sometimes be hard to see. A minor adjustment could make this configurable by introducing col.rug as an argument, like this:

ggPD_boot<-function (gbm.object,predictor = NULL,n.plots = length(pred.names),list.4.preds=NULL,booted.preds=NULL, nrow=NULL,ncol=NULL,
                     col.line="darkorange",cex.line=0.5, type.ci="lines",col.ci= "grey80",cex.ci=0.3,lty.ci=2, alpha.ci=0.5,smooth = FALSE,
                     col.smooth="blue",cex.smooth=0.3,span=0.3,rug = FALSE,rug.pos="t", **col.rug = "#EBEBEB"**, common.scale = TRUE,cis=c(0.025, 0.975),
                     y.label = "Fitted function",x.label=NULL,...){

Then, you could incorporate col.rug like this in lines 172,198,269,295:

        if (rug==T){
          ggPD<-ggPD+geom_rug(data=fittedVal,aes(x=x,y=y),sides=rug.pos,position="jitter",color=col.rug)
        }

Thank you once again for your generosity in sharing this tool. Looking forward to seeing more of your work in the future!

Warm regards,

Alba

**Comment by JBjouffray** [comment]
Hi Alba,

Thanks for your kind words and helpful efforts to improve ggBRT. I have now updated ggPD_boot based on your suggestions. Thanks a lot!

All the best,
Jean-Baptiste
